apiVersion: apps/v1
kind: Deployment
metadata:
  name: skatakamlab28
  labels:
    app: skatakamwebnginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: skatakamnnginxwebpod
  template:
    metadata:
      labels:
        app: skatakamnginxwebpod
    spec:
      containers:
      - name: nginx
        image: sktakam123/lab28:1.0.0
        imagePullPolicy: Always 
---
apiVersion: v1 
kind: Service 
metadata: 
    name: skatakamlab28 
spec: 
   selector: 
     app: skatakamnginxwebpod 
   type: NodePort
   ports: 
        - protocol: TCP 
          port: 80 
          targetPort: 80 
